version: '3.8'

services:
  teams_api:
    build:
      context: .
      dockerfile: ./src/base/docker/Dockerfile
      args:
        PROJECT_DIR: ${PROJECT_DIR}
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./src:$PROJECT_DIR
      - static_volume:$PROJECT_DIR/static
      - media_volume:$PROJECT_DIR/media
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py create_admin &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  static_volume:
  media_volume:
