# Generated by Django 5.0.1 on 2024-01-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_way',
            field=models.CharField(choices=[('registration', 'Registration'), ('google', 'Google')], default=('registration', 'Registration'), max_length=50),
        ),
    ]
