# Generated by Django 5.0.1 on 2024-01-16 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_registration_way'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='registration_way',
            new_name='registration_method',
        ),
    ]
