# Generated by Django 5.0.1 on 2024-01-13 18:36

import teams_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=teams_app.models.LowercaseEmailField(max_length=254),
        ),
    ]
